# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Update API Docs

on:
    push:
        branches: ["production"]
    workflow_dispatch:

env:
    BRANCH: production

jobs:
    build:
        runs-on: macos-latest

        strategy:
            matrix:
                node-version: [18.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
              with:
                  path: code
            - uses: actions/checkout@v3
              with:
                  path: docs
                  repository: Smithed-MC/Docs
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
                  cache-dependency-path: "**/package-lock.json"
            - run: npm i
              working-directory: ./code
            - run: npx turbo run lint --filter=data-types --filter=doc-generator -- --noEmit false
              working-directory: ./code
            - name: Generate Docs
              run: DOC_REPO="${GITHUB_WORKSPACE}/docs" node index.js
              working-directory: ./code/packages/doc-generator
            - name: Push Docs to repo
              working-directory: ./docs
              run: |
                cd docs
                git config --global user.name 'Git bot'
                git config --global user.email 'bot@noreply.github.com'
                git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Smithed-MC/Docs
                git commit -am "deploy: Auto updated API docs" && git push || echo "No changes to commit"