# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Update API Docs

on:
    push:
        branches: ["production"]
    workflow_dispatch:

env:
    BRANCH: production

jobs:
    build:
        runs-on: macos-latest

        strategy:
            matrix:
                node-version: [18.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
              with:
                  path: code
            - uses: actions/checkout@v3
              with:
                  path: docs
                  repository: Smithed-MC/Docs
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
                  cache-dependency-path: "**/package-lock.json"
            - run: npm i
              working-directory: ./code
            - run: cat code/node_modules/ts-node/package.json | grep version
            - name: Generate Docs
              run: DOC_REPO="${GITHUB_WORKSPACE}/docs" npx turbo run generate --filter=doc-generator
              working-directory: ./code
