# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Website CI - Main Branch

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        environment: ci
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
            - run: npx turbo run build --filter=api --filter=website
            - run: npm run test
              env:
                SMITHED_EMAIL: ${{ secrets.SMITHED_EMAIL }}
                SMITHED_PASSWORD: ${{ secrets.SMITHED_PASSWORD }}
            - name: Deploy to DevOps
              uses: peter-evans/repository-dispatch@v2
              with:
                  token: ${{ secrets.PAT }}
                  repository: Smithed-MC/DevOps
                  event-type: update
                  client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "module": "main", "branch": "main"}'